### ISSUE TITLE
Support for v2+ of a package

### ISSUE THREAD

**Issue by tj** [tj/gobinaries#10]
Go Modules is a bit of a mess, requiring `/v2` or similar in the package path, so we'll have to account for that.

**Comment by derekcollison** [comment]
Would like to direct folks to use this for simple installs of master for https://nats.io server but we are V2. So upvote from us!

Let us know how we can help.

**Comment by tj** [comment]
@derekcollison awesome thanks! I'm not super familiar with Go modules yet when it comes to `> v1`. I wonder if it makes more sense to copy Go's path style such as `https://github.com/tj/whatever/v2 | sh`, but I still like the semver stuff it would be great to get that working.

**Comment by derekcollison** [comment]
The whole v1 to v2 was not much fun for sure. Will see if we can help out.
