### ISSUE TITLE
keep a local list of installed stuff

### ISSUE THREAD

**Issue by caarlos0** [tj/gobinaries#23]
## Prerequisites

* [x] I searched to see if the issue already exists.

## Description

I have my computer  "as code", so I use brew to dump all things I have installed and can easily reinstall them later.

Would be nice to have a `~/.gobinaries` file with something like:

```
rakyll/hey
tj/staticgen/cmd/staticgen@1.x
# etc ...
```

so we could easily reinstall all with something like

```sh
while read -r line; do
  curl -sf "https://gobinaries.com/$line" | sh
done <~/.gobinaries
```

## Steps to Reproduce

-

## Slack

Join us on Slack https://chat.apex.sh/

**Comment by tj** [comment]
sounds reasonable to me! I guess the only question is how many people would use it, but it shouldn't hurt

**Comment by caarlos0** [comment]
yeah, pretty much add a `echo path >> ~/.gobinaries` :)
