### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by suconghou** [tj/gobinaries#30]
https://github.com/evanw/esbuild/issues/66

```
https://gobinaries.com/binary/github.com/evanw/esbuild?os=darwin&arch=amd64&version=v0.3.9
```
Internal Server Error

**Comment by tj** [comment]
hmm it should be providing a better error, I'll look into that, but you have to provide the full path to a command (there could be many), for example this worked:

```
$ curl -sf https://gobinaries.com/evanw/esbuild/cmd/esbuild | PREFIX=. sh
$ ./esbuild -h
```
